### ISSUE TITLE
Data visualization appendix

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/arrowtooth#1]
Mostly based on what is in the synopsis report pages:

- [x] survey spatial plots (as in pcod https://github.com/pbs-assess/pacific-cod-2020/blob/master/R/plot-survey-sets.R and perhaps modelled too)
- [x] catch plot
- [x] stitched survey
- [x] time series cpue
- [x] spatial catch and cpue (TODO: make colour axis log?)
- [x] maturity fit (by region and coastwide)
- [x] VB fit (by region and coastwide)
- [x] bubble plots
- [x] length histograms

Look in 10-figures.Rmd for chunk label style, but fine (easiest?) to work in separate minimal csasdown resdoc for now.

French and English versions. If adding custom labels beyond what is already in gfplot, have to be in `en2fr()` and text has to be in rossetafish dictionary.

Work with output from `cache_pbs_data()`.

**Comment by seananderson** [comment]
![image](https://user-images.githubusercontent.com/19349/185470320-5838d1cc-eabc-493c-b401-53a46f9fd219.png)

**Comment by seananderson** [comment]
![image](https://user-images.githubusercontent.com/19349/185470462-4386f0c0-0e93-4845-92dc-cd616b37b2fe.png)

**Comment by seananderson** [comment]
State privacy rule here and squash outliers (or use log colours)?

![image](https://user-images.githubusercontent.com/19349/185471122-d44d3101-2430-4337-8e62-ecd248250b5b.png)

**Comment by ecophilina** [comment]
> State privacy rule here and squash outliers (or use log colours)?

done this

**Comment by ecophilina** [comment]
I've added drafts of the remaining of these to the figures.rmd for now, but I imagine some will need to be moved to an appendix.
