### ISSUE TITLE
Check index standardized residuals correct

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/arrowtooth#10]
Look better I think, but still surprised ones like WCVI outliers are within -1 +1 standardized

![image](https://user-images.githubusercontent.com/19349/185471866-8d27532d-e0b4-446a-b9ab-c1a430a3d23b.png)
![image](https://user-images.githubusercontent.com/19349/185471897-08f3cb15-80de-40d2-ae99-0f8045d723a6.png)

**Actually, those index CIs should be +/- 2 SEs (in log space!) not +/- CV in natural space... that could explain it**

**Comment by cgrandin** [comment]
I had to create some new variables inside the iSCAM code and output the log standard residuals.

This is correct, and the weight (`wt`) values for the survey indices are `1/re` where `re` is the BOOT_RE column in the BOOT_DETAILS table in GFBioSQL. `re` is not in log space, so I logged them prior to standardizing them for each index and multiplying them by the annual indices in ISCAM. That makes a tiny bit of difference. Here's what they look like now (WCHG is removed from the model):

![image](https://user-images.githubusercontent.com/4551051/185993552-1b614c05-960d-4711-9c7d-daef84ced8fe.png)

**Comment by cgrandin** [comment]
>  Actually, those index CIs should be +/- 2 SEs (in log space!) not +/- CV in natural space

The plotted index CI's are the `lowerci` and `upperci` columns supplied by the bootstrap method and returned from `gfdata::get_survey_index()`. They have to be in natural space

**Comment by seananderson** [comment]
There shouldn’t be any logging of the CV (re column). Can you point me to
the code?

**Comment by cgrandin** [comment]
From here:
https://github.com/pbs-assess/gfiscam/blob/a16b06d714d1f43d8e6416172bc467a286a6fe24/src/main/iscam.tpl#L2351
to here:
https://github.com/pbs-assess/gfiscam/blob/a16b06d714d1f43d8e6416172bc467a286a6fe24/src/main/iscam.tpl#L2362

I just logged wt before standardizing it (line 2352) on the next line (2353), but it makes almost no difference anyway.  The real change is on line 2360 where the residuals standardization is

**Comment by cgrandin** [comment]
See https://github.com/pbs-assess/gfiscam/commit/a16b06d714d1f43d8e6416172bc467a286a6fe24 and https://github.com/pbs-assess/gfiscam/commit/fd579a18112e1ebe37d95585f0073007bcec4b0b

This was checked by running this code on the base model:

```map(base_model$mcmc$std_epsilon, ~{.x |> unlist() |> length()})```

Which show all the SD's as close to 1
