### ISSUE TITLE
Age-at-50% in models is higher than what appears in the plots

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/arrowtooth#11]
@seananderson : We had a discussion about which function to use to extract the age-at-50% parameters for, and since iSCAM just uses the two parameters to re-create the logistic we agreed to use the one I wrote which is here: https://github.com/pbs-assess/arrowtooth/blob/d4cc8efa07886b35e77b7ae39d5c9d824b262894/R/export-mat-lw-age.R#L82

But, the new plots (Currently Fig 3) show that the values are at most 5.9 for females and 4.5 for males using `gfplot::fit_mat_ogive()`. My code estimates higher ages (see values below)  along with the shape (or scale) parameter. `gfplot::fit_mat_ogive()` doesn't produce the second parameter.

All the models have been run with these:

Female         Male
 6.2381463  5.2441949 # -age at 50% maturity
 1.6467835  2.0430129 # -std at 50% maturity

**Comment by seananderson** [comment]
Yep, Philina added that figure but didn’t know. Separately, Quang recently
added the cauchit link, which he found fit quillback best.

**Comment by cgrandin** [comment]
Fixed in 5405bb4d599152db221c303817efa5bded5bd09b
