### ISSUE TITLE
Is there a way to show the major areas on the catch/cpue spatial map?

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/arrowtooth#12]
Something like this...

![image](https://user-images.githubusercontent.com/4551051/186271522-09ac68f6-bca2-4dd2-88ff-4254c5b392d3.png)

Or is there some other way that is usually done?

**Comment by seananderson** [comment]
They're available in PBSdata. E.g. https://github.com/ecophilina/ye-wcvi/blob/a4f92e681ff7fbb68d928a6a55c7b620216c80aa/analysis/functions.R#L203-L206

Maybe @ecophilina could add them?

**Comment by cgrandin** [comment]
That would be awesome, on the catch and cpue figures. I moved the other ones to an appendix so they are first in the Figures Rmd file now
