### ISSUE TITLE
Parameter word subscripts would ideally not be italics

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/arrowtooth#2]
E.g. `\mathrm{male}`

`ln` should be `\ln`

`log` should be `\log` (if present at all?)

![image](https://user-images.githubusercontent.com/19349/185464970-fc7cb03c-821b-4048-85be-fec4a3e28034.png)
![image](https://user-images.githubusercontent.com/19349/185465000-4a196154-6fd2-4db7-85b5-925d560765bf.png)

**Comment by cgrandin** [comment]
Resolved in 37551d87290b8bd8e80087451b0c9f78e2119a38 and https://github.com/pbs-assess/gfiscamutils/commit/1aa15cfa6650e060dcfa0256f8ed2ccd628732bd
