### ISSUE TITLE
2 different greens being used

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/arrowtooth#9]
![image](https://user-images.githubusercontent.com/19349/185471389-311b1216-f037-4209-b7c1-a89930ed6e88.png)
![image](https://user-images.githubusercontent.com/19349/185471407-4cf1be9b-9b34-481f-9107-5055d43fa6d4.png)

I think I'd prefer the first more muted one.

Also, can we make one dashed for the colour blind?

**Comment by cgrandin** [comment]
Those are the defaults in the function call, which are different because you can have both ref points on the same plot but yes, easy to make both the first one.

**Comment by cgrandin** [comment]
Resolved in https://github.com/pbs-assess/gfiscamutils/commit/21b20a0ab32433b233bc3a58435f471fb76b3b11
